CREATE TABLE IF NOT EXISTS review_item_feedbacks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  item_fingerprint VARCHAR(128) NOT NULL,
  card_id VARCHAR(128) NULL,
  risk_id VARCHAR(128) NULL,
  review_key VARCHAR(64) NULL,
  finding_index INT NULL,
  risk_type VARCHAR(64) NULL,
  risk_title VARCHAR(255) NULL,
  original_risk_level VARCHAR(32) NULL,
  feedback_type VARCHAR(64) NOT NULL,
  reason_type VARCHAR(64) NULL,
  reason_text TEXT NULL,
  suggest_as_project_rule BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  admin_comment TEXT NULL,
  item_snapshot_json JSON NULL,
  operator_name VARCHAR(128) NULL,
  operator_username VARCHAR(128) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_review_item_feedback_task_source_item (task_id, source_type, item_fingerprint),
  KEY idx_review_item_feedback_project_status_created (project_id, status, created_at),
  KEY idx_review_item_feedback_project_type (project_id, feedback_type),
  KEY idx_review_item_feedback_source_item (source_type, item_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
