CREATE TABLE IF NOT EXISTS code_quality_finding_refinements (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  review_key VARCHAR(64) NOT NULL DEFAULT 'default',
  finding_index INT NOT NULL,
  fingerprint VARCHAR(128) NULL,
  finding_id VARCHAR(128) NULL,
  project_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  trigger_reason VARCHAR(255) NULL,
  trigger_conditions_json JSON NOT NULL,
  retrieval_plan_json JSON NULL,
  evidence_summary_json JSON NULL,
  missing_context_json JSON NULL,
  failure_reason VARCHAR(1024) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_code_quality_refinement_task_review_finding (task_id, review_key, finding_index),
  KEY idx_code_quality_refinements_task_review (task_id, review_key),
  KEY idx_code_quality_refinements_fingerprint (fingerprint),
  KEY idx_code_quality_refinements_project_created (project_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
